# Dependabot configuration for waybar-amd-module
# This configuration enables automated dependency updates for the Go ecosystem

version: 2
updates:
  # Go module dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Allow up to 5 open pull requests for Go modules
    open-pull-requests-limit: 5
    # Group patch and minor updates to reduce PR noise
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Configure commit message format
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Reviewer configuration - uncomment and customize if needed
    # reviewers:
    #   - "bnema"
    # assignees:
    #   - "bnema"
    # Target branch for PRs (defaults to repository default branch)
    target-branch: "main"
    # Ignore specific dependencies that shouldn't be auto-updated
    # ignore:
    #   - dependency-name: "github.com/spf13/cobra"
    #     versions: [">=2.0.0"]  # Example: ignore major version updates